abstract: 
    api_version: 5
    # extends:

#opts:
#    minify: false


# modules section is for registering application modules
# you can read more detailed about modules format here - https://github.com/EugeneN/cafe/wiki/recipe-file
modules:
    - jquery: npm://commonjs-jquery
    - libprotein: npm://libprotein
    - console-logger: npm://console-logger
    - libmonad: npm://libmonad
    - libprotocol: npm://libprotocol
    - dna: npm://dna-lang
    - idom: npm://dc-idom
    - ihelper-jquery: npm://dc-helper


# Section for defining your bundles structure
bundles:
    bundle1:
        modules:
            - jquery
            - libprotein
            - console-logger
            - libmonad
            - libprotocol
            - idom
            - ihelper-jquery
            - dna
